//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram")]

namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass RAARMAPMCWeberMDDDiagram
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("f3b6001e-6f0d-45d8-b57a-214814d6cc37")]
	public partial class RAARMAPMCWeberMDDDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.Entidad)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.EntidadShape newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.EntidadShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimShape newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.Relacion)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.RelacionShape newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.RelacionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRelShape newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRelShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEntShape newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEntShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.RelAtrib newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.RelAtrib(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.RelIzq newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.RelIzq(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer)
			{
				global::UPM_IPS.RAARMAPMCWeberMDD.RelDer newShape = new global::UPM_IPS.RAARMAPMCWeberMDD.RelDer(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.RAARMAPMCWeberMDD.EntidadShape.DecoratorsInitialized += EntidadShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimShape.DecoratorsInitialized += ClavePrimShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.RelacionShape.DecoratorsInitialized += RelacionShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRelShape.DecoratorsInitialized += AtributoRelShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEntShape.DecoratorsInitialized += AtributoEntShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.RelIzq.DecoratorsInitialized += RelIzqDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.RAARMAPMCWeberMDD.RelDer.DecoratorsInitialized += RelDerDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for EntidadShape.
		/// </summary>
		internal static partial class EntidadShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for EntidadShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.Entidad.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClavePrimShape.
		/// </summary>
		internal static partial class ClavePrimShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClavePrimShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RelacionShape.
		/// </summary>
		internal static partial class RelacionShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RelacionShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.Relacion.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AtributoRelShape.
		/// </summary>
		internal static partial class AtributoRelShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AtributoRelShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AtributoEntShape.
		/// </summary>
		internal static partial class AtributoEntShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AtributoEntShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "DecNombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RelIzq.
		/// </summary>
		internal static partial class RelIzqDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RelIzq.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.cardinalidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for RelDer.
		/// </summary>
		internal static partial class RelDerDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for RelDer.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.cardinalidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.RAARMAPMCWeberMDD.RelAtribConnectAction relAtribConnectAction;
		private global::UPM_IPS.RAARMAPMCWeberMDD.RelIzqConnectAction relIzqConnectAction;
		private global::UPM_IPS.RAARMAPMCWeberMDD.RelDerConnectAction relDerConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDToolboxHelper.RelAtribFilterString))
				{
					if (this.relAtribConnectAction == null)
					{
						this.relAtribConnectAction = new global::UPM_IPS.RAARMAPMCWeberMDD.RelAtribConnectAction(this);
						this.relAtribConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relAtribConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDToolboxHelper.RelIzqFilterString))
				{
					if (this.relIzqConnectAction == null)
					{
						this.relIzqConnectAction = new global::UPM_IPS.RAARMAPMCWeberMDD.RelIzqConnectAction(this);
						this.relIzqConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relIzqConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDToolboxHelper.RelDerFilterString))
				{
					if (this.relDerConnectAction == null)
					{
						this.relDerConnectAction = new global::UPM_IPS.RAARMAPMCWeberMDD.RelDerConnectAction(this);
						this.relDerConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relDerConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.relAtribConnectAction != null)
					{
						this.relAtribConnectAction.Dispose();
						this.relAtribConnectAction = null;
					}
					if(this.relIzqConnectAction != null)
					{
						this.relIzqConnectAction.Dispose();
						this.relIzqConnectAction = null;
					}
					if(this.relDerConnectAction != null)
					{
						this.relDerConnectAction.Dispose();
						this.relDerConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// RAARMAPMCWeberMDDDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf3b6001e, 0x6f0d, 0x45d8, 0xb5, 0x7a, 0x21, 0x48, 0x14, 0xd6, 0xcc, 0x37);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RAARMAPMCWeberMDDDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public RAARMAPMCWeberMDDDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.Entidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.Relacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.RAARMAPMCWeberMDD.Entidad)
				{
					parentElement = GetParentForEntidad((global::UPM_IPS.RAARMAPMCWeberMDD.Entidad)childElement);
				} else
				if(childElement is global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria)
				{
					parentElement = GetParentForClavePrimaria((global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria)childElement);
				} else
				if(childElement is global::UPM_IPS.RAARMAPMCWeberMDD.Relacion)
				{
					parentElement = GetParentForRelacion((global::UPM_IPS.RAARMAPMCWeberMDD.Relacion)childElement);
				} else
				if(childElement is global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel)
				{
					parentElement = GetParentForAtributoRel((global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel)childElement);
				} else
				if(childElement is global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt)
				{
					parentElement = GetParentForAtributoEnt((global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD GetParentForEntidad( global::UPM_IPS.RAARMAPMCWeberMDD.Entidad root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD result = root.WebERMDD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD GetParentForClavePrimaria( global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RAARMAPMCWeberMDD.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD result = root2.WebERMDD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD GetParentForRelacion( global::UPM_IPS.RAARMAPMCWeberMDD.Relacion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD result = root.WebERMDD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD GetParentForAtributoRel( global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD result = root.WebERMDD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD GetParentForAtributoEnt( global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt root )
			{
				// Segments 0 and 1
				global::UPM_IPS.RAARMAPMCWeberMDD.Entidad root2 = root.Entidad;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD result = root2.WebERMDD;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.cardinalidadDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.RAARMAPMCWeberMDD.RelIzq.FindRelIzqDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.cardinalidadDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.RAARMAPMCWeberMDD.RelDer.FindRelDerDecorator("NameDecorator");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram diagram = linkShape.Diagram as global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
