//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainModel RAARMAPMCWeberMDDDomainModel
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDD
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("ad746184-f6ca-4762-9f37-49a27b5c03be")]
	public partial class RAARMAPMCWeberMDDDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// RAARMAPMCWeberMDDDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xad746184, 0xf6ca, 0x4762, 0x9f, 0x37, 0x49, 0xa2, 0x7b, 0x5c, 0x03, 0xbe);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public RAARMAPMCWeberMDDDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(WebERMDD),
				typeof(Entidad),
				typeof(AtributoEnt),
				typeof(Relacion),
				typeof(AtributoRel),
				typeof(ClavePrimaria),
				typeof(WebERMDDHasElements),
				typeof(WebERMDDHasRelacion),
				typeof(EntidadHasAtributoEnt),
				typeof(EntidadHasClavePrimaria),
				typeof(RelacionReferencesAtributoRel),
				typeof(WebERMDDHasAtributoRel),
				typeof(RelacionReferencesEntidadIzq),
				typeof(RelacionReferencesEntidadDer),
				typeof(RAARMAPMCWeberMDDDiagram),
				typeof(RelIzq),
				typeof(RelDer),
				typeof(RelAtrib),
				typeof(EntidadShape),
				typeof(AtributoEntShape),
				typeof(AtributoRelShape),
				typeof(ClavePrimShape),
				typeof(RelacionShape),
				typeof(global::UPM_IPS.RAARMAPMCWeberMDD.FixUpDiagram),
				typeof(global::UPM_IPS.RAARMAPMCWeberMDD.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.RAARMAPMCWeberMDD.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(WebERMDD), "nombre", WebERMDD.nombreDomainPropertyId, typeof(WebERMDD.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Entidad), "nombre", Entidad.nombreDomainPropertyId, typeof(Entidad.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnt), "nombre", AtributoEnt.nombreDomainPropertyId, typeof(AtributoEnt.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnt), "tipo", AtributoEnt.tipoDomainPropertyId, typeof(AtributoEnt.tipoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnt), "nulo", AtributoEnt.nuloDomainPropertyId, typeof(AtributoEnt.nuloPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "nombre", Relacion.nombreDomainPropertyId, typeof(Relacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRel), "nombre", AtributoRel.nombreDomainPropertyId, typeof(AtributoRel.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRel), "tipo", AtributoRel.tipoDomainPropertyId, typeof(AtributoRel.tipoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRel), "nulo", AtributoRel.nuloDomainPropertyId, typeof(AtributoRel.nuloPropertyHandler)),
				new DomainMemberInfo(typeof(ClavePrimaria), "nombre", ClavePrimaria.nombreDomainPropertyId, typeof(ClavePrimaria.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClavePrimaria), "tipo", ClavePrimaria.tipoDomainPropertyId, typeof(ClavePrimaria.tipoPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesEntidadIzq), "cardinalidad", RelacionReferencesEntidadIzq.cardinalidadDomainPropertyId, typeof(RelacionReferencesEntidadIzq.cardinalidadPropertyHandler)),
				new DomainMemberInfo(typeof(RelacionReferencesEntidadDer), "cardinalidad", RelacionReferencesEntidadDer.cardinalidadDomainPropertyId, typeof(RelacionReferencesEntidadDer.cardinalidadPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(WebERMDDHasElements), "WebERMDD", WebERMDDHasElements.WebERMDDDomainRoleId),
				new DomainRolePlayerInfo(typeof(WebERMDDHasElements), "Element", WebERMDDHasElements.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(WebERMDDHasRelacion), "WebERMDD", WebERMDDHasRelacion.WebERMDDDomainRoleId),
				new DomainRolePlayerInfo(typeof(WebERMDDHasRelacion), "Relacion", WebERMDDHasRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEnt), "Entidad", EntidadHasAtributoEnt.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasAtributoEnt), "AtributoEnt", EntidadHasAtributoEnt.AtributoEntDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "Entidad", EntidadHasClavePrimaria.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadHasClavePrimaria), "ClavePrimaria", EntidadHasClavePrimaria.ClavePrimariaDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRel), "Relacion", RelacionReferencesAtributoRel.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesAtributoRel), "AtributoRel", RelacionReferencesAtributoRel.AtributoRelDomainRoleId),
				new DomainRolePlayerInfo(typeof(WebERMDDHasAtributoRel), "WebERMDD", WebERMDDHasAtributoRel.WebERMDDDomainRoleId),
				new DomainRolePlayerInfo(typeof(WebERMDDHasAtributoRel), "AtributoRel", WebERMDDHasAtributoRel.AtributoRelDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidadIzq), "Relacion", RelacionReferencesEntidadIzq.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidadIzq), "Entidad", RelacionReferencesEntidadIzq.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidadDer), "Relacion", RelacionReferencesEntidadDer.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionReferencesEntidadDer), "Entidad", RelacionReferencesEntidadDer.EntidadDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(15);
				createElementMap.Add(typeof(WebERMDD), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(AtributoEnt), 2);
				createElementMap.Add(typeof(Relacion), 3);
				createElementMap.Add(typeof(AtributoRel), 4);
				createElementMap.Add(typeof(ClavePrimaria), 5);
				createElementMap.Add(typeof(RAARMAPMCWeberMDDDiagram), 6);
				createElementMap.Add(typeof(RelIzq), 7);
				createElementMap.Add(typeof(RelDer), 8);
				createElementMap.Add(typeof(RelAtrib), 9);
				createElementMap.Add(typeof(EntidadShape), 10);
				createElementMap.Add(typeof(AtributoEntShape), 11);
				createElementMap.Add(typeof(AtributoRelShape), 12);
				createElementMap.Add(typeof(ClavePrimShape), 13);
				createElementMap.Add(typeof(RelacionShape), 14);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new WebERMDD(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new AtributoEnt(partition, propertyAssignments);
				case 3: return new Relacion(partition, propertyAssignments);
				case 4: return new AtributoRel(partition, propertyAssignments);
				case 5: return new ClavePrimaria(partition, propertyAssignments);
				case 6: return new RAARMAPMCWeberMDDDiagram(partition, propertyAssignments);
				case 7: return new RelIzq(partition, propertyAssignments);
				case 8: return new RelDer(partition, propertyAssignments);
				case 9: return new RelAtrib(partition, propertyAssignments);
				case 10: return new EntidadShape(partition, propertyAssignments);
				case 11: return new AtributoEntShape(partition, propertyAssignments);
				case 12: return new AtributoRelShape(partition, propertyAssignments);
				case 13: return new ClavePrimShape(partition, propertyAssignments);
				case 14: return new RelacionShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(WebERMDDHasElements), 0);
				createElementLinkMap.Add(typeof(WebERMDDHasRelacion), 1);
				createElementLinkMap.Add(typeof(EntidadHasAtributoEnt), 2);
				createElementLinkMap.Add(typeof(EntidadHasClavePrimaria), 3);
				createElementLinkMap.Add(typeof(RelacionReferencesAtributoRel), 4);
				createElementLinkMap.Add(typeof(WebERMDDHasAtributoRel), 5);
				createElementLinkMap.Add(typeof(RelacionReferencesEntidadIzq), 6);
				createElementLinkMap.Add(typeof(RelacionReferencesEntidadDer), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new WebERMDDHasElements(partition, roleAssignments, propertyAssignments);
				case 1: return new WebERMDDHasRelacion(partition, roleAssignments, propertyAssignments);
				case 2: return new EntidadHasAtributoEnt(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadHasClavePrimaria(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionReferencesAtributoRel(partition, roleAssignments, propertyAssignments);
				case 5: return new WebERMDDHasAtributoRel(partition, roleAssignments, propertyAssignments);
				case 6: return new RelacionReferencesEntidadIzq(partition, roleAssignments, propertyAssignments);
				case 7: return new RelacionReferencesEntidadDer(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return RAARMAPMCWeberMDDDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (RAARMAPMCWeberMDDDomainModel.resourceManager == null)
				{
					RAARMAPMCWeberMDDDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(RAARMAPMCWeberMDDDomainModel).Assembly);
				}
				return RAARMAPMCWeberMDDDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return RAARMAPMCWeberMDDDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return RAARMAPMCWeberMDDDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RAARMAPMCWeberMDDDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new RAARMAPMCWeberMDDCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					RAARMAPMCWeberMDDDomainModel.copyClosure = copyFilter;
				}
				return RAARMAPMCWeberMDDDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (RAARMAPMCWeberMDDDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new RAARMAPMCWeberMDDDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					RAARMAPMCWeberMDDDomainModel.removeClosure = removeFilter;
				}
				return RAARMAPMCWeberMDDDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RAARMAPMCWeberMDDDeleteClosure : RAARMAPMCWeberMDDDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RAARMAPMCWeberMDDDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RAARMAPMCWeberMDDDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public RAARMAPMCWeberMDDDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.ElementDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.AtributoEntDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.AtributoRelDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RAARMAPMCWeberMDDCopyClosure : RAARMAPMCWeberMDDCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RAARMAPMCWeberMDDCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class RAARMAPMCWeberMDDCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public RAARMAPMCWeberMDDCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

