//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass WebERMDD
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.WebERMDD.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.WebERMDD.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("9cf5a778-b702-4a24-a785-3412e5f4f8bc")]
	public partial class WebERMDD : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// WebERMDD domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x9cf5a778, 0xb702, 0x4a24, 0xa7, 0x85, 0x34, 0x12, 0xe5, 0xf4, 0xf8, 0xbc);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WebERMDD(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public WebERMDD(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xafe75f4a, 0x6d31, 0x4bdf, 0x80, 0x81, 0xed, 0x92, 0xc3, 0x56, 0x47, 0xd7);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.WebERMDD.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.WebERMDD/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.WebERMDD/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("afe75f4a-6d31-4bdf-8081-ed92c35647d7")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the WebERMDD.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<WebERMDD, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the WebERMDD.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the WebERMDD.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(WebERMDD element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(WebERMDD element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Elements opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Elements
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.WebERMDDDomainRoleId);
			}
		}
		#endregion
		#region Relacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacion.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.WebERMDD
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.WebERMDDDomainRoleId);
			}
		}
		#endregion
		#region AtributoRel opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRel.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.WebERMDD
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRel> AtributoRel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRel>, AtributoRel>(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.WebERMDDDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.RAARMAPMCWeberMDD.Entidad.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.RAARMAPMCWeberMDD.Relacion.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.RAARMAPMCWeberMDD.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.Entidad;
			if (sourceEntidad1 != null)
			{
				// Create link for path WebERMDDHasElements.Elements
				this.Elements.Add(sourceEntidad1);

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.Relacion sourceRelacion2 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.Relacion;
			if (sourceRelacion2 != null)
			{
				// Create link for path WebERMDDHasRelacion.Relacion
				this.Relacion.Add(sourceRelacion2);

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel sourceAtributoRel3 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel;
			if (sourceAtributoRel3 != null)
			{
				// Create link for path WebERMDDHasAtributoRel.AtributoRel
				this.AtributoRel.Add(sourceAtributoRel3);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.RAARMAPMCWeberMDD.Entidad sourceEntidad1 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.Entidad;
			if (sourceEntidad1 != null)
			{
				// Delete link for path WebERMDDHasElements.Elements
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.GetLinks((global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD)this, sourceEntidad1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.WebERMDDDomainRoleId, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.ElementDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.Relacion sourceRelacion2 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.Relacion;
			if (sourceRelacion2 != null)
			{
				// Delete link for path WebERMDDHasRelacion.Relacion
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.GetLinks((global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD)this, sourceRelacion2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.WebERMDDDomainRoleId, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.RelacionDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel sourceAtributoRel3 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.AtributoRel;
			if (sourceAtributoRel3 != null)
			{
				// Delete link for path WebERMDDHasAtributoRel.AtributoRel
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.GetLinks((global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDD)this, sourceAtributoRel3))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.WebERMDDDomainRoleId, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.AtributoRelDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass Entidad
	/// Elements embedded in the model. Appear as boxes on the diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.Entidad.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.Entidad.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (nombre = {nombrePropertyStorage})")]
	[DslModeling::DomainObjectId("40dd1189-1b7a-46f1-a57f-af8599aa384b")]
	public partial class Entidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x40dd1189, 0x1b7a, 0x46f1, 0xa5, 0x7f, 0xaf, 0x85, 0x99, 0xaa, 0x38, 0x4b);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xe738ea38, 0x0606, 0x4b8c, 0x96, 0x5c, 0x4e, 0x4f, 0xaf, 0xf6, 0x62, 0xaa);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.Entidad.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.Entidad/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.Entidad/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("e738ea38-0606-4b8c-965c-4e4faff662aa")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Entidad.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Entidad, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Entidad.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Entidad.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Entidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Entidad element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region WebERMDD opposite domain role accessor
		/// <summary>
		/// Gets or sets WebERMDD.
		/// </summary>
		public virtual WebERMDD WebERMDD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.ElementDomainRoleId) as WebERMDD;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasElements.ElementDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoEnt opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoEnt.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoEnt> AtributoEnt
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEnt>, AtributoEnt>(global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.EntidadDomainRoleId);
			}
		}
		#endregion
		#region ClavePrimaria opposite domain role accessor
		/// <summary>
		/// Gets or sets ClavePrimaria.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.Entidad
		/// </summary>
		public virtual ClavePrimaria ClavePrimaria
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.EntidadDomainRoleId) as ClavePrimaria;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region RelacionIzq opposite domain role accessor
		
		/// <summary>
		/// Gets a list of RelacionIzq.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> RelacionIzq
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.EntidadDomainRoleId);
			}
		}
		#endregion
		#region RelacionDer opposite domain role accessor
		
		/// <summary>
		/// Gets a list of RelacionDer.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> RelacionDer
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.EntidadDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.DomainClassId)) 
				{
					// Check that creating a link with this path doesn't cause multiplicity overflow: EntidadHasClavePrimaria.ClavePrimaria
					if (this.ClavePrimaria != null)
					{
						return false;
					}
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt sourceAtributoEnt1 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt;
			if (sourceAtributoEnt1 != null)
			{
				// Create link for path EntidadHasAtributoEnt.AtributoEnt
				this.AtributoEnt.Add(sourceAtributoEnt1);

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria sourceClavePrimaria2 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria;
			if (sourceClavePrimaria2 != null)
			{
				// Create link for path EntidadHasClavePrimaria.ClavePrimaria
				this.ClavePrimaria = sourceClavePrimaria2;

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt sourceAtributoEnt1 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt;
			if (sourceAtributoEnt1 != null)
			{
				// Delete link for path EntidadHasAtributoEnt.AtributoEnt
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.GetLinks((global::UPM_IPS.RAARMAPMCWeberMDD.Entidad)this, sourceAtributoEnt1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.EntidadDomainRoleId, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.AtributoEntDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria sourceClavePrimaria2 = sourceElement as global::UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria;
			if (sourceClavePrimaria2 != null)
			{
				// Delete link for path EntidadHasClavePrimaria.ClavePrimaria
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.GetLinks((global::UPM_IPS.RAARMAPMCWeberMDD.Entidad)this, sourceClavePrimaria2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.EntidadDomainRoleId, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass AtributoEnt
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("21cabc20-c553-42b8-96a1-da07185c2665")]
	public partial class AtributoEnt : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoEnt domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x21cabc20, 0xc553, 0x42b8, 0x96, 0xa1, 0xda, 0x07, 0x18, 0x5c, 0x26, 0x65);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEnt(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEnt(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xe76d6ac9, 0xf841, 0x40e1, 0x98, 0x16, 0x7e, 0xe7, 0x66, 0x0a, 0x30, 0x8a);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("e76d6ac9-f841-40e1-9816-7ee7660a308a")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoEnt.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoEnt, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoEnt.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoEnt.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AtributoEnt element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoEnt element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region tipo domain property code
		
		/// <summary>
		/// tipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid tipoDomainPropertyId = new global::System.Guid(0xd7aeee3a, 0x2483, 0x4b74, 0x8a, 0xf2, 0xa2, 0x32, 0x13, 0xf2, 0x7f, 0x63);
		
		/// <summary>
		/// Storage for tipo
		/// </summary>
		private global::System.String tipoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tipo domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/tipo.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/tipo.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("d7aeee3a-2483-4b74-8af2-a23213f27f63")]
		public global::System.String tipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tipoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoEnt.tipo domain property.
		/// </summary>
		internal sealed partial class tipoPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoEnt, global::System.String>
		{
			private tipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoEnt.tipo domain property value handler.
			/// </summary>
			public static readonly tipoPropertyHandler Instance = new tipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoEnt.tipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AtributoEnt element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoEnt element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region nulo domain property code
		
		/// <summary>
		/// nulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid nuloDomainPropertyId = new global::System.Guid(0x4545fa6b, 0xa26a, 0x43c9, 0xaa, 0x78, 0x3b, 0xe2, 0xc6, 0x91, 0x5a, 0x46);
		
		/// <summary>
		/// Storage for nulo
		/// </summary>
		private global::System.Boolean nuloPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of nulo domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt.Nulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/nulo.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoEnt/nulo.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("4545fa6b-a26a-43c9-aa78-3be2c6915a46")]
		public global::System.Boolean nulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nuloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nuloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoEnt.nulo domain property.
		/// </summary>
		internal sealed partial class nuloPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoEnt, global::System.Boolean>
		{
			private nuloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoEnt.nulo domain property value handler.
			/// </summary>
			public static readonly nuloPropertyHandler Instance = new nuloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoEnt.nulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nuloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Boolean GetValue(AtributoEnt element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nuloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoEnt element, global::System.Boolean newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Boolean oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nuloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.AtributoEnt
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.AtributoEntDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasAtributoEnt.AtributoEntDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass Relacion
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.Relacion.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.Relacion.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("7dae86ab-3e8f-4f30-9a30-27b8817de2b0")]
	public partial class Relacion : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x7dae86ab, 0x3e8f, 0x4f30, 0x9a, 0x30, 0x27, 0xb8, 0x81, 0x7d, 0xe2, 0xb0);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xa4496575, 0x6c71, 0x4d15, 0xba, 0x77, 0x09, 0x88, 0x24, 0x05, 0x28, 0x93);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.Relacion.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.Relacion/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.Relacion/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("a4496575-6c71-4d15-ba77-098824052893")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region WebERMDD opposite domain role accessor
		/// <summary>
		/// Gets or sets WebERMDD.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.Relacion
		/// </summary>
		public virtual WebERMDD WebERMDD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.RelacionDomainRoleId) as WebERMDD;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasRelacion.RelacionDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoRel opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRel.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRel> AtributoRel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRel>, AtributoRel>(global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel.RelacionDomainRoleId);
			}
		}
		#endregion
		#region EntidadIzq opposite domain role accessor
		/// <summary>
		/// Gets or sets EntidadIzq.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.Relacion
		/// </summary>
		public virtual Entidad EntidadIzq
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.RelacionDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadIzq.RelacionDomainRoleId, value);
			}
		}
		#endregion
		#region EntidadDer opposite domain role accessor
		/// <summary>
		/// Gets or sets EntidadDer.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.Relacion
		/// </summary>
		public virtual Entidad EntidadDer
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.RelacionDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesEntidadDer.RelacionDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass AtributoRel
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoRel
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("0b114390-2a0b-481a-a25e-7ac515a7212d")]
	public partial class AtributoRel : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoRel domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x0b114390, 0x2a0b, 0x481a, 0xa2, 0x5e, 0x7a, 0xc5, 0x15, 0xa7, 0x21, 0x2d);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRel(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRel(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0x9b690765, 0x84ca, 0x4f8e, 0xbc, 0x8c, 0x1b, 0xce, 0x73, 0x3e, 0xd1, 0x73);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("9b690765-84ca-4f8e-bc8c-1bce733ed173")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoRel.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoRel, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoRel.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoRel.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AtributoRel element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoRel element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region tipo domain property code
		
		/// <summary>
		/// tipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid tipoDomainPropertyId = new global::System.Guid(0x1cfbc47c, 0xca8d, 0x47bf, 0xb1, 0xf5, 0xcd, 0xdd, 0x65, 0x68, 0x79, 0x01);
		
		/// <summary>
		/// Storage for tipo
		/// </summary>
		private global::System.String tipoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tipo domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/tipo.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/tipo.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("1cfbc47c-ca8d-47bf-b1f5-cddd65687901")]
		public global::System.String tipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tipoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoRel.tipo domain property.
		/// </summary>
		internal sealed partial class tipoPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoRel, global::System.String>
		{
			private tipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoRel.tipo domain property value handler.
			/// </summary>
			public static readonly tipoPropertyHandler Instance = new tipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoRel.tipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AtributoRel element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoRel element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region nulo domain property code
		
		/// <summary>
		/// nulo domain property Id.
		/// </summary>
		public static readonly global::System.Guid nuloDomainPropertyId = new global::System.Guid(0x1aedf72e, 0xc5ce, 0x4d2f, 0x8b, 0xf5, 0x19, 0x88, 0x1f, 0xbc, 0x3a, 0xfb);
		
		/// <summary>
		/// Storage for nulo
		/// </summary>
		private global::System.Boolean nuloPropertyStorage;
		
		/// <summary>
		/// Gets or sets the value of nulo domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.AtributoRel.Nulo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/nulo.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.AtributoRel/nulo.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("1aedf72e-c5ce-4d2f-8bf5-19881fbc3afb")]
		public global::System.Boolean nulo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nuloPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nuloPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoRel.nulo domain property.
		/// </summary>
		internal sealed partial class nuloPropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoRel, global::System.Boolean>
		{
			private nuloPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoRel.nulo domain property value handler.
			/// </summary>
			public static readonly nuloPropertyHandler Instance = new nuloPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoRel.nulo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nuloDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.Boolean GetValue(AtributoRel element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nuloPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoRel element, global::System.Boolean newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.Boolean oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nuloPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Relacion opposite domain role accessor
		/// <summary>
		/// Gets or sets Relacion.
		/// Description for
		/// UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel.AtributoRel
		/// </summary>
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel.AtributoRelDomainRoleId) as Relacion;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.RelacionReferencesAtributoRel.AtributoRelDomainRoleId, value);
			}
		}
		#endregion
		#region WebERMDD opposite domain role accessor
		/// <summary>
		/// Gets or sets WebERMDD.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.AtributoRel
		/// </summary>
		public virtual WebERMDD WebERMDD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.AtributoRelDomainRoleId) as WebERMDD;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.WebERMDDHasAtributoRel.AtributoRelDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	/// <summary>
	/// DomainClass ClavePrimaria
	/// Description for UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("9c0cdfa0-558c-4198-8f6c-78ce6eef2bc4")]
	public partial class ClavePrimaria : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// ClavePrimaria domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x9c0cdfa0, 0x558c, 0x4198, 0x8f, 0x6c, 0x78, 0xce, 0x6e, 0xef, 0x2b, 0xc4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClavePrimaria(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClavePrimaria(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xbeeb1caa, 0xa2d7, 0x4672, 0x88, 0x11, 0x87, 0xea, 0x49, 0x35, 0xff, 0xd8);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria/nombre.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria/nombre.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("beeb1caa-a2d7-4672-8811-87ea4935ffd8")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the ClavePrimaria.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<ClavePrimaria, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the ClavePrimaria.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the ClavePrimaria.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(ClavePrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(ClavePrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region tipo domain property code
		
		/// <summary>
		/// tipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid tipoDomainPropertyId = new global::System.Guid(0x21cd37fe, 0x5894, 0x438c, 0xa8, 0x0f, 0x46, 0xe2, 0x68, 0x82, 0x8d, 0x9a);
		
		/// <summary>
		/// Storage for tipo
		/// </summary>
		private global::System.String tipoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tipo domain property.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria.Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria/tipo.DisplayName", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.RAARMAPMCWeberMDD.ClavePrimaria/tipo.Description", typeof(global::UPM_IPS.RAARMAPMCWeberMDD.RAARMAPMCWeberMDDDomainModel), "UPM_IPS.RAARMAPMCWeberMDD.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("21cd37fe-5894-438c-a80f-46e268828d9a")]
		public global::System.String tipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tipoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the ClavePrimaria.tipo domain property.
		/// </summary>
		internal sealed partial class tipoPropertyHandler : DslModeling::DomainPropertyValueHandler<ClavePrimaria, global::System.String>
		{
			private tipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the ClavePrimaria.tipo domain property value handler.
			/// </summary>
			public static readonly tipoPropertyHandler Instance = new tipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the ClavePrimaria.tipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(ClavePrimaria element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(ClavePrimaria element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Description for UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.ClavePrimaria
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.RAARMAPMCWeberMDD.EntidadHasClavePrimaria.ClavePrimariaDomainRoleId, value);
			}
		}
		#endregion
	}
}
