//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.RAARMAPMCWeberMDD
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "RRPWeber";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RAARMAPMCWeberMDD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RAARMAPMCWeberMDDDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RAARMAPMCWeberMDDCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RAARMAPMCWeberMDDExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RAARMAPMCWeberMDDCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRAARMAPMCWeberMDDExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RAARMAPMCWeberMDDCommandSetId), 0x0001);
	
		// Package identifier
		public const string RAARMAPMCWeberMDDPackageId = "c69cfe43-b3da-4556-bfd5-f2ad858e1dce";
		
		// Editor factory identifier
		public const string RAARMAPMCWeberMDDEditorFactoryId = "8852f546-9c49-4323-86a2-977794a4e035";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RAARMAPMCWeberMDDModelExplorerToolWindowId = "4443f274-3741-493e-82fa-2694fd527095";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.RAARMAPMCWeberMDD
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RAARMAPMCWeberMDDCommandSetId = "0fc22009-e230-49f3-9670-547ea14917eb";
	}
}